services:
  library:
    build:
      dockerfile: Dockerfile
    environment:
      - DEBUG=false
    ports:
      - "8000:8000"
  
  mysql:
    image: mysql:9.2
    ports:
      - "3306:3306"
    env_file: "library/.env"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: {}
