# Generated by Django 5.1.6 on 2025-06-12 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 12, 22, 18, 38, 387189)),
        ),
    ]
