# Generated by Django 5.1.6 on 2025-06-12 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_author_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='slug',
        ),
    ]
