# Generated by Django 5.1.6 on 2025-06-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_remove_author_slug_remove_book_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
