# Generated by Django 5.1.6 on 2025-06-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_author_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='price',
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
