# Generated by Django 5.1.6 on 2025-06-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_remove_author_price_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
