# Generated by Django 5.1.6 on 2025-06-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_book_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
