# Generated by Django 5.1.6 on 2025-06-13 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_book_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='quantity',
        ),
    ]
