# Generated by Django 5.1.6 on 2025-06-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='real_name',
            field=models.CharField(default='noname', max_length=100),
            preserve_default=False,
        ),
    ]
