# Generated by Django 5.1.6 on 2025-06-13 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_real_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
    ]
