# Generated by Django 5.1.6 on 2025-06-13 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_products_ordersbooks'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordersbooks',
            table='orders_books',
        ),
    ]
